---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ compose_path }}"
    state: absent
  when: >
    compose_current_version.stdout is defined
    and compose_version not in compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ compose_path }}"
    mode: 0755
