---
- include_tasks: setup-RedHat.yml

- name: Install Docker.
  package:
    name: "{{ package }}"
    state: "{{ package_state }}"
  notify: restart docker
  tags:
    - full-install

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  tags:
    - full-install

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  tags:
    - full-install

- include_tasks: docker-compose.yml
  when: install_compose
  tags:
    - full-install

- include_tasks: docker-users.yml
  when: users
  tags:
    - full-install
