---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ edition }}.repo'
    section: 'docker-{{ edition }}-edge'
    option: enabled
    value: '{{ yum_repo_enable_edge }}'

- name: Configure Docker Test repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ edition }}.repo'
    section: 'docker-{{ edition }}-test'
    option: enabled
    value: '{{ yum_repo_enable_test }}'
